require("dotenv").config()

let MONGODB_URI = process.env.MONGODB_URL
let DEV_MONGODB_URI = process.env.DEV_MONGODB_URL
let CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
let SECRET = process.env.SECRET
let CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME
let CLOUDINARY_SECRET = process.env.CLOUDINARY_SECRET
let MAPBOX_TOKEN = process.env.MAPBOX_TOKEN
module.exports = {
  MONGODB_URI,
  CLOUDINARY_API_KEY,
  SECRET,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_SECRET,
  MAPBOX_TOKEN,
  DEV_MONGODB_URI,
}
